### ISSUE TITLE
droxi does not work with ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]

### ISSUE THREAD

**Issue by ildar-aim** [jangler/droxi#5]
# Short log

### Worked
cormorant[~]$ ruby --version
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]
cormorant[~]$ droxi         
Logged in as Ildar Amankulov (public.ildar@gmail.com)
droxi public.ildar@gmail.com:/> 
cormorant[~]$ 

### Failed
cormorant[~]$ ruby --version
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]
cormorant[~]$ droxi
/usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- dropbox_sdk (LoadError)
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/bin/droxi:1209:in `<main>'

# Full log
```
cormorant[~]$ ruby --version         
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]
cormorant[~]$ droxi
Logged in as Ildar Amankulov (public.ildar@gmail.com)
droxi public.ildar@gmail.com:/> 
cormorant[~]$ downgrade ruby
Available packages:

   1) ruby-2.2.0-1-x86_64.pkg.tar.xz (local)
   2) ruby-2.1.5-1-x86_64.pkg.tar.xz (local)
   3) ruby-2.1.5-1-x86_64.pkg.tar.xz (remote)
   4) ruby-2.1.4-1-x86_64.pkg.tar.xz (remote)
   5) ruby-2.1.3-2-x86_64.pkg.tar.xz (remote)
   6) ruby-2.1.2-1-x86_64.pkg.tar.xz (remote)
   7) ruby-2.1.1-2-x86_64.pkg.tar.xz (remote)
   8) ruby-2.1.1-1-x86_64.pkg.tar.xz (remote)
   9) ruby-2.1.0-2-x86_64.pkg.tar.xz (remote)
  10) ruby-2.0.0_p353-1-x86_64.pkg.tar.xz (remote)

select a package by number: 1
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) ruby-2.2.0-1

Total Installed Size:  20.23 MiB
Net Upgrade Size:       1.93 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                                                                                     [####################################################################] 100%
(1/1) checking package integrity                                                                                   [####################################################################] 100%
(1/1) loading package files                                                                                        [####################################################################] 100%
(1/1) checking for file conflicts                                                                                  [####################################################################] 100%
(1/1) checking available disk space                                                                                [####################################################################] 100%
(1/1) upgrading ruby                                                                                               [####################################################################] 100%
New optional dependencies for ruby
    tk: for Ruby/TK
cormorant[~]$ ruby --version
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]
cormorant[~]$ droxi
/usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- dropbox_sdk (LoadError)
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/bin/droxi:1209:in `<main>'
cormorant[~]$ downgrade ruby
Available packages:

   1) ruby-2.2.0-1-x86_64.pkg.tar.xz (local)
   2) ruby-2.1.5-1-x86_64.pkg.tar.xz (local)
   3) ruby-2.1.5-1-x86_64.pkg.tar.xz (remote)
   4) ruby-2.1.4-1-x86_64.pkg.tar.xz (remote)
   5) ruby-2.1.3-2-x86_64.pkg.tar.xz (remote)
   6) ruby-2.1.2-1-x86_64.pkg.tar.xz (remote)
   7) ruby-2.1.1-2-x86_64.pkg.tar.xz (remote)
   8) ruby-2.1.1-1-x86_64.pkg.tar.xz (remote)
   9) ruby-2.1.0-2-x86_64.pkg.tar.xz (remote)
  10) ruby-2.0.0_p353-1-x86_64.pkg.tar.xz (remote)

select a package by number: 2
loading packages...
warning: downgrading package ruby (2.2.0-1 => 2.1.5-1)
resolving dependencies...
looking for conflicting packages...

Packages (1) ruby-2.1.5-1

Total Installed Size:  18.30 MiB
Net Upgrade Size:      -1.93 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                                                                                     [####################################################################] 100%
(1/1) checking package integrity                                                                                   [####################################################################] 100%
(1/1) loading package files                                                                                        [####################################################################] 100%
(1/1) checking for file conflicts                                                                                  [####################################################################] 100%
(1/1) checking available disk space                                                                                [####################################################################] 100%
(1/1) downgrading ruby                                                                                             [####################################################################] 100%
cormorant[~]$ ruby --version
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]
cormorant[~]$ droxi
Logged in as Ildar Amankulov (public.ildar@gmail.com)
droxi public.ildar@gmail.com:/> 
```

**Comment by ildar-aim** [comment]
cormorant[~]$ droxi --version
droxi v0.2.3
cormorant[~]$

**Comment by jangler** [comment]
If you just run `gem install dropbox-sdk` you should be good to go. I'm going to look into this problem a bit more though, since it's a pain that a Ruby upgrade breaks the gem environment. Thanks for the report!

**Comment by jangler** [comment]
Commit cf0b0d5e574faf69fb4eacdc8a32dc7a0f352731 handles the `LoadError` by telling the user that they need to (re)install the gem in order to continue.

When you install droxi through the AUR, the `dropbox-sdk` gem is automatically installed, but a new Ruby version can't access a gem installed for an older Ruby version by any means that I know of.

I think that attempting to automatically install the gem at runtime would be out of line, and probably error-prone. So this is as good as it gets.

**Comment by ildar-aim** [comment]
Thank you for the quick fix!
It works now.
```
cormorant[~]$ droxi --version
droxi v0.2.3
cormorant[~]$ ruby --version 
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]
```

**Comment by jangler** [comment]
Added [an AUR package](https://aur.archlinux.org/packages/ruby-dropbox-sdk/) for dropbox-sdk and made the droxi package require that instead of just installing the gem, but I think this will still be an issue.
